# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Poll For WhatsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poll For WhatsApp
  pod 'CountryKit'                        #https://github.com/tinrobots/CountryKit
  pod 'SwifterSwift'                      #https://github.com/SwifterSwift/SwifterSwift
  pod 'IHKeyboardAvoiding'                #https://github.com/IdleHandsApps/IHKeyboardAvoiding
  pod 'SwiftyStoreKit'                    #https://github.com/bizz84/SwiftyStoreKit

  pod 'PieCharts'                        #https://github.com/i-schuetz/PieCharts
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/DynamicLinks'
  
end
